URL_CONTRIBUTION_GUIDE = "https://design.gitlab.com/get-started/contributing/#contribute-a-merge-request"
COMMIT_SUBJECT_MAX_LENGTH = 72
COMMIT_BODY_MAX_LENGTH = 72

# Commit messages that start with one of the prefixes below won't be linted
IGNORED_COMMIT_MESSAGES = [
  'Merge branch',
  'Revert "'
].freeze

# Perform various checks against commits. We're not using
# https://github.com/jonallured/danger-commit_lint because its output is not
# very helpful, and it doesn't offer the means of ignoring merge commits.

def fail_commit(commit, message)
    fail("#{commit.sha}: #{message}") # rubocop:disable Style/SignalException
end

def warn_commit(commit, message)
  warn("#{commit.sha}: #{message}")
end

def lines_changed_in_commit(commit)
  commit.diff_parent.stats[:total][:lines]
end

def too_many_changed_lines?(commit)
  commit.diff_parent.stats[:total][:files] > 3 &&
    lines_changed_in_commit(commit) >= 30
end

def lint_commit(commit)
  # For now we'll ignore merge commits, as getting rid of those is a problem
  # separate from enforcing good commit messages.
  # We also ignore revert commits as they are well structured by Git already
  if commit.message.start_with?(*IGNORED_COMMIT_MESSAGES)
    return { failed: false, release: NO_RELEASE }
  end

  ## Suggestions applied through GitLab UI are not enforced as
  ## long as the squash option is enabled.
  if commit.message.match(/^.*?\bApply\b.*?\bsuggestion\b.*?$/m) && helper.squash_mr?
    appliedSuggestion = true
    return { failed: false, release: NO_RELEASE }
  end  

  failed = false
  subject, separator, details = commit.message.split("\n", 3)

  if subject.length > COMMIT_SUBJECT_MAX_LENGTH
    fail_commit(
      commit,
      "The commit subject may not be longer than #{COMMIT_SUBJECT_MAX_LENGTH} characters"
    )

    failed = true
  end

  # Warn if a suggestion commit is used and squash is not enabled.
  if commit.message.match(/^.*?\bApply\b.*?\bsuggestion\b.*?$/m) && !helper.squash_mr?
    warn_commit(
      commit,
      'This MR contains applied suggestions, but the squash commits option is disabled. If you are a maintainer merging this MR, please enable the squash commits option before merging.'
    )
    
    appliedSuggestion = true
    failed = false
  end

  if subject.end_with?('.')
    fail_commit(commit, 'The commit subject must not end with a period')
    failed = true
  end

  if separator && !separator.empty?
    fail_commit(
      commit,
      'The commit subject and body must be separated by a blank line'
    )

    failed = true
  end

  details&.each_line do |line|
    line = line.strip

    next if line.length <= COMMIT_BODY_MAX_LENGTH

    url_size = line.scan(%r{(https?://\S+)}).sum { |(url)| url.length }

    # If the line includes a URL, we'll allow it to exceed 72 characters, but
    # only if the line _without_ the URL does not exceed this limit.
    next if line.length - url_size <= COMMIT_BODY_MAX_LENGTH

    fail_commit(
      commit,
      "The commit body should not contain more than #{COMMIT_BODY_MAX_LENGTH} characters per line"
    )

    failed = true
  end

  if !details && too_many_changed_lines?(commit)
    fail_commit(
      commit,
      'Commits that change 30 or more lines across at least three files ' \
        'must describe these changes in the commit body'
    )

    failed = true
  end

  if commit.message.match?(%r{([\w\-\/]+)?(#|!|&|%)\d+\b})
    fail_commit(
      commit,
      'Use full URLs instead of short references ' \
        '(`gitlab-org/gitlab-ce#123` or `!123`), as short references are ' \
        'displayed as plain text outside of GitLab'
    )

    failed = true
  end

  { failed: failed, release: release }
end

def lint_commits(commits)
  commits_with_status = commits.map { |commit| { commit: commit }.merge(lint_commit(commit)) }

  failed = commits_with_status.any? { |commit| commit[:failed] }

  if failed
    markdown(<<~MARKDOWN)
      ## Commit message standards

      One or more commit messages do not meet our Git commit message standards.
      For more information on how to write a good commit message, take a look at
      [the contribution guide](#{URL_CONTRIBUTION_GUIDE}).

      Here is an example of a good commit message:

          feat(progressbar): Improve rendering performance in Edge

          Our progressbar component was causing a lot of re-renders in Edge.
          This was caused by excessive re-rendering due to floating point errors
          in Edge's JavaScript engine.

          By utilizing the better-math library we avoid those calculation errors
          and we can achieve 120 rendering frames per second again.

      This is an example of a bad commit message:

          fixed progressbar

    MARKDOWN
  end

  return if helper.squash_mr?
end

def lint_mr(mr_title)
  return if mr_title.empty?
end

lint_commits(git.commits)
lint_mr(helper.mr_title) if helper.squash_mr?

if git.commits.length > 10
  warn(
    'This merge request includes more than 10 commits. ' \
      'Please rebase these commits into a smaller number of commits.'
  )
end
