---
config:
  default: true
  line-length: false
  no-inline-html: false
  first-line-heading:
    front_matter_title: 'name'
  no-duplicate-heading:
    siblings_only: true
  no-emphasis-as-heading: false
